A lot of changes in module town.

diff --git a/bin/git-rm-submodule b/bin/git-rm-submodule
--- a/bin/git-rm-submodule
+++ b/bin/git-rm-submodule
@@ -29,7 +29,7 @@ mod_line_p=$((mod_line+1))
 # determine the line of the next submodule, to delete all lines between.
 mod_line_end=$(grep -n "\[submodule" $gitmod | cut -f1 -d: | grep -A1 $mod_line | tail -n1)
 # if there is no module after this, delete to the end of the file
-if [ $mod_line -eq $mod_line_end ]; then mod_line_end=$(wc -l $gitmod); fi
+if [ $mod_line -eq $mod_line_end ]; then mod_line_end=$(wc -l $gitmod | cut -f1 -d' '); fi
 
 # determine the line of the submodule in .git/config
 conf_line=$(grep -n "\[submodule .*$module.*\]" $gitconf | cut -f1 -d:)
@@ -40,7 +40,7 @@ mod_path=$(sed -n "$mod_line_p p" $gitmod | grep -oP '\w*path = \K.*')
 
 
 # delete from .gitmodules
-if ! sed "$mod_line,$mod_line_end d" $gitmod; then
+if ! sed -i.orig "$mod_line,$mod_line_end d" $gitmod; then
    echo "Could not delete lines $mod_line - $mod_line_end from gitmodules."
    exit 1
 fi
@@ -51,7 +51,7 @@ if ! git add $gitmod; then
 fi
 
 # delete from .git/config
-if ! sed "$conf_line,$conf_line_end d" $gitconf; then
+if ! sed -i.orig "$conf_line,$conf_line_end d" $gitconf; then
    echo "Could not delete lines $conf_line - $conf_line_end from gitmodules."
    exit 1
 fi
@@ -65,13 +65,13 @@ if ! rm -rf .git/modules/$mod_path; then
    echo "Could not remove module from internal git storage."
 fi
 
-if ! git submit -m "Deleted submodule $MODULE"; then
-   echo "Could not check in changed $GITMOD file."
+if ! git ci -m "Deleted submodule $module"; then
+   echo "Could not check in changed $gitmod file."
    exit 1
 fi
 
-if ! rm -rf $MOD_PATH; then
-  echo "Could not remove module path $PATH"
+if ! rm -rf $mod_path; then
+  echo "Could not remove module path $path"
   exit 1
 fi
 
